### ISSUE TITLE
Create Todo Items API

### ISSUE THREAD

**Issue by ArisKallergis** [ArisKallergis/todos#5]
We need the Todo Items API finished in order to merge with main and push version to 0.8.0

- [x] Show all items of a todo
- [x] Show a specific item of a todo
- [x] Create a new item in a todo
- [x] Update an item of a todo
- [x] Delete an item of a todo

**Comment by ArisKallergis** [comment]
created
